services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file: django/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: django/.env
    restart: unless-stopped
    
  nginx:
    build:
      context: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - django
  
volumes:
  db-data:
