services:
  db:
    image: postgres
    container_name: db
    ports:
        - "5432:5432"
    env_file: .env
    volumes:
        - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
  
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./django:/django
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./nginx/certs/selfsigned.crt:/etc/nginx/conf/server.crt
      - ./nginx/certs/selfsigned.key:/etc/nginx/conf/server.key
      - ./nginx/conf/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./nginx/conf/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./nginx/conf/modsecurity.conf:/etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template
    restart: unless-stopped