services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./django
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/db

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - app

volumes:
  postgres_data: