# Generated by Django 5.1.1 on 2024-10-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_friends_profile_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Darius: The Hand of Noxus, a brutal warrior with a deadly axe.'),
        ),
    ]
