# Generated by Django 5.1.1 on 2024-09-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapSettings',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
