# Generated by Django 5.1.1 on 2024-09-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='game_party',
        ),
    ]
